### ISSUE TITLE
[BUG] - Gif files

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs-aviary#1]
Hello everyone,

I noticed that if the user:

1. Drags and drops a grapesjs image block into the canvas

1. Selects a GIF

1. Edits it using aviary tool and saves

1. The animated GIF in the canvas will become a still image, even though the extension of the file will still be `.gif`

I suggest that either this bug should be fixed or hiding the edit button using aviary in the image block, in case the selected image is a GIF.

Thank you.

**Comment by artf** [comment]
I think this is something not related to grapesjs itself but how GIFs are handled by the Aviary Editor. If you don't want to open the editor on GIF images you can extend the original `image` component and implement your logic.
