### ISSUE TITLE
Images are not showing on clicking the aviary icon on image

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-aviary#3]
When I click on the aviary Icon on Image, Its doesn't show the image and gives the error on console.

**Failed to load resource: the server responded with a status of 503 (Service Unavailable: Back-end server is at capacity)**

https://featherservices.aviary.com/imgjsonpserver.aspx?callback=jQuery171096878174270254_1548143538727&url=http%253A%2F%2Fplacehold.it%2F350x250%2F78c5d6%2Ffff%2Fimage1.jpg&_=1548143554702

The image url example: http://placehold.it/350x250/78c5d6/fff/image1.jpg

Please help me, how to fix this issue. Thanks

**Comment by artf** [comment]
@NorthstarTech Aviary was shutted down something like a year ago

**Comment by NorthstarTech** [comment]
@artf, Then how we will edit the images if Aviary was closed. Its also not working on your demo. Please provide the alternate for it. Thanks

**Comment by artf** [comment]
@NorthstarTech create your own plugin with any image editor you want... use this repo code as an example
